import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1 className='text-5xl'>James Stroker</h1>
      <p className='bg-red-300 text-5xl'>
        Almost before we knew it, we had left the ground.
      </p>
    </div>
  )
}
